services:


  db:
    image: mongo:8.0-noble
    restart: always
    container_name: domnor-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    env_file:
      - ./backend/.env
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - domnor-net

volumes:
  mongo-data:
    driver: local

networks:
  domnor-net:
    driver: bridge
